apps/product/urls.py
from django.urls import path
from apps.product import views

app_name = 'product'

urlpatterns = [
    path('', views.index , name='index'),
    path('produtos/', views.listAllProducts, name='allProducts'),
    path('produtos/<slug:slug>/', views.detail, name='details-product'),
    path('cadastrar',views.cadastrar, name='cadastrar'),
    path('editar/<slug:slug>',views.editProduto, name='editProduct')
]

apps/user/urls.py
from django.urls import path, include
#from django.contrib.auth import authenticate
from apps.user import views
from django.contrib.auth.views import LoginView
app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('registrar-se/', views.register, name='register'),
    path('sair/',views.logoutview,name='logout'),
    path('perfil/',views.dashboard, name='perfil'),
    path('ver-produtos/',views.productOfClient, name='meus-produtos'),
    path('editar-conta/',views.editAccount, name='editar-conta'),
    path('editar-senha/',views.editPassword, name='editar-password')
]

easySale_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('apps.product.urls', namespace='product')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

apps/product/models.py
from django.db import models
#from django.contrib.auth import get_user_model
from easySale_System import settings

#User = get_user_model()
class CustomManager(models.Manager):

    def getForName(self, name):
        return self.all().filter(name=name)

    def allProducts(self):
        return self.all()

    def getProductsForUser(self , user):
        return self.all().filter(cpfUserPost=user)

    def getSlug(self, slug):
        return self.all().filter(slug=slug)


class Product(models.Model):
    name = models.CharField('Nome do Produto' , max_length=50)
    slug = models.SlugField(unique=True)
    preco = models.DecimalField(verbose_name='Preço do produto' , max_digits=10 , decimal_places=2)
    datePost = models.DateField(auto_now_add=True)  
    tipyDept = models.CharField('Departamento' , null=False , blank=False , max_length=20)
    description = models.TextField('Descrição do produto',max_length=200 )
    littleDescription = models.TextField('Curta descrição',max_length=50 )
    juros = models.BooleanField( null=False , blank=False)
    image = models.ImageField(verbose_name="Imagem do Produto", upload_to='product/images',null=True, blank=True )
    maxParc = models.IntegerField(verbose_name='Total de Parcelas')
    cpfUserPost = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    totalVendas = models.IntegerField('Total vendidos',default=0,null=False)

    objects = CustomManager()
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return self.slug

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['id']



class Coment(models.Model):
    comentario = models.TextField('Comentário do produto',max_length=200 )
    nota = models.DecimalField('Nota', max_digits=10,decimal_places=1)
    title = models.TextField("Titulo do comentario",max_length=50)
    produto = models.ForeignKey(Product, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ['nota']

apps/product/forms.py
from django import forms
from .models import Product
from django.forms import (
    NumberInput,TextInput, CheckboxInput,CheckboxSelectMultiple,Select,FileInput
    )


FAVORITE_COLORS_CHOICES = (
	('outros','Outros'),
    ('informatica', 'Informática'),
    ('som', 'Som'),
    ('roupas', 'Roupas'),
    ('computadores','Computadores'),
    ('comidas','comidas')

)
class InsertProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['cpfUserPost', 'slug', 'totalVendas']
        widgets = {
            'name': TextInput( attrs={'placeholder': 'nome do produto','class':'form-control'}),
            'description':TextInput(attrs={'placeholder':'Descrição do produto','class':'form-control'}),
            'preco':NumberInput(attrs={'placeholder':'Preco do produto','class':'form-control','min':'0.1'}),
            'juros':CheckboxInput(),
            'maxParc':NumberInput( attrs={'min':'1','max':'24' ,'class':'form-control'}),
            'tipyDept': Select(choices=FAVORITE_COLORS_CHOICES, attrs={'class':'custom-select'}),
            'image':FileInput(attrs={'class':'custom-file-input'}),
            'littleDescription' : TextInput(attrs={'placeholder':'digite uma pequena descrição do produto','class':'form-control', 'maxlength':'50'})

        }


class SeachProduto(forms.Form):
	nome = forms.CharField()

apps/product/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import (InsertProduct)
from django.utils.text import slugify
from django.contrib import messages
#from django.http import HttpResponse
# Views da app produto.

from .models import Product
def index(request):
    return render(request, 'home.html')


def listAllProducts(request):
    produtos = Product.objects.allProducts()


    context ={
        'produtos': produtos
    }

    return render(request ,'listProducts.html', context)
@login_required()
def cadastrar(request):
    if request.method == 'POST':
        form = InsertProduct(request.POST)
        if (form.is_valid()):
            produto = form.save(commit=False)
            count = 1
            produto.slug = slugify(form.cleaned_data['name'])
            while Product.objects.all().filter(slug=produto.slug).exists():
                count+=1
                produto.slug = slugify(form.cleaned_data['name'])
                produto.slug+=str(count)

            produto.cpfUserPost = request.user
            produto.save()
            messages.add_message(request, messages.SUCCESS, 'PRODUTO CADASTRADO.')
            return redirect('product:allProducts')
    else:
        form = InsertProduct()
    context = {
        'form': form
    }
    return render(request, 'cadastra.html', context)

def detail(request, slug):
    produto = Product.objects.get(slug=slug)
    produto.parcelas = round(produto.preco/produto.maxParc , 2)
    context = {
        'produto':produto
    }
    return render(request , 'details.html', context)

def searchName(request, name):
    produtos = Product.objects.searchName(name=name)
    context = {
        'produtos': produtos
    }
    return render(request, templantename , context)


def editProduto(request , slug):
    produto = Product.objects.all().filter(slug=slug).first()
    if request.method == 'POST':
        form = InsertProduct(request.POST ,instance=produto )
        print(form.errors)
        if (form.is_valid()):
            print(' valido')
            produto = form.save(commit=False)
            produto.slug = slugify(form.cleaned_data['name'])
            produto.cpfUserPost = request.user
            produto.save()
            messages.add_message(request, messages.INFO, 'Produto editado')
            return redirect('product:details-product', slug=produto.slug)
    else:
        print('else')
        form = InsertProduct(instance=produto)
    context = {
        'form': form
    }
    return render(request, 'edit-produtt.html', context)

apps/product/templates/base.html
</!DOCTYPE html>
<html>
<head>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <!--fontes-->
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Kaushan+Script|Lobster|Montserrat|Shadows+Into+Light" rel="stylesheet">
  {%block definitionsMeta%}
  
  {% endblock%}
</head>
<body>
	<div class="wraper" >
		<div class="header1">
			<div class="header1-item">
				<ul class="midias-sociais">
					<li class="facebook-svg "><a class="trasparent" href="#face" >facebook</a></li>
					<li class="instagram-svg "><a  class="trasparent" href="#insta">instagram</a></li>
					<li class="git-svg "><a class="trasparent" href="#git"></a></li>
				</ul>
			</div>
			<div>
				<p>
					Compre conosco, que cuidaremos de tudo!
				</p>
			</div>
			<div>
				<p>
					<a class="contact" href="mailto:webmaster@example.com">supportsuacompra@gmail.com</a>
				</p>
			</div>
		</div>


		<nav class="nav-menu" id="nav_bar">
			<div><h3 class="brand"> <a href="{%url 'product:index'%}">SuaCompra.</a></h3></div>
			<div>
				<ul class="menu-itens">
					<li ><a href="{%url 'product:index'%}">Home</a></li>
					<li>
						<a class="drop-menu">Departamentos</a>
						<ul class="sub_menu">
							<li><a href="#">Computadores</a></li>
							<li><a href="#">informatica</a></li>
							<li><a href="#">microprocesador</a></li>
						</ul>
					</li>
					<li><a>Ofertas</a></li>
					<li><a href="{%url 'product:allProducts'%}">Produtos</a></li>
				</ul>
			</div>
			<div>
				<div>
					<ul class="menu-options">
						{% if user.is_authenticated %}
							<li>
								<div class="btn-group">

									  <button type="button" class="dropdown-toggle btn btn-outline-secondary btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}
									  </button>
									  <div class="dropdown-menu">
									    <a class="dropdown-item" href="{% url 'user:perfil' %}">Perfil</a>
									    <a class="dropdown-item" href=" {% url 'user:meus-produtos'  %}">Ver meus produtos</a>
									    <a class="dropdown-item" href="{% url 'product:cadastrar' %}">Cadastrar produto</a>
									    <a class="dropdown-item" href="#">Registrar-se</a>
									    <div class="dropdown-divider"></div>
									    <a class="dropdown-item" href="{%url 'user:logout'%}">Sair </a>
									    
									  </div>
								</div>
							</li>
						{%else%}
							<li>
								<div class="btn-group">
									  <button type="button" class="dropdown-toggle accounts trasparent" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									  </button>
									  <div class="dropdown-menu">
									    <a class="dropdown-item" href="{% url 'user:login'%}">Entrar</a>
									    <a class="dropdown-item" href="{% url 'user:register' %}">Registrar-se</a>  
									  </div>
								</div>
							</li>
						{%endif%}
						<li class="divider trasparent"></li>
						<li class="bag trasparent"><a>Carrinho</a></li>
					</ul>
				</div>
		</div>
		</div>
	</nav>	
</div>

{% if messages %}
{% for message in messages %}
<div class="modal fade" id="modal-information" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" id="modal-information">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Atenção!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p {% if message.tags %} class='{{ message.extra_tags }}' {% endif %}>{{ message }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}
{% block contentPage %}


{% endblock %}
<footer class="footer-contet">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="content-information" id="entre-em-contato">
					<h5>Entre em contato</h5>
					<div class="">
						<p>
						  Alguma pergunta? Deixe-nos saber na loja no 8º andar, 379 Hudson St, Nova York, NY 10018 ou ligue para (+1) 96 716 6879
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-2">
		        <div>
		          <h5>Categorias</h5>  
		            <ul class="list-details">
		              <li><a>Para homens</a></li>
		              <li><a>Para mulheres</a></li>
		              <li><a>Para crianças</a></li>
		              <li><a>Todos</a></li>
		            </ul>
		        </div>	
			</div>
			<div class="col-md-2">
		        <div>
		  				<h5>Links úteis</h5>
		          <ul class="list-details">
		              <li><a>Pesquise</a></li>
		              <li><a>contate-nos</a></li>
		              <li><a>Sobre nós</a></li>
		              <li><a>Feedback</a></li>
		          </ul>
		        </div>
			</div>
			<div class="col-md-2">
		        <div>
						  <h5>Ajuda</h5>
		          <ul class="list-details">
		            <li><a>Segurança</a></li>
		            <li><a>Sobre nós</a></li>
		            <li><a>Nossas avaliações</a></li>
		            <li><a>FAQs</a></li>
		          </ul>
				</div>
	      	</div>
			<div class="col-md-3">
		        <div class="content-information">
		  				<h5>Notificações de promoções</h5>
		  				<div>
		            <label for="inscricao">se inscreva </label>
		              <input type="email" name="inscricao" placeholder="seuemail@dominio.com" id="inscricao" class="form-control">
		              <p>Nós enviaremos apenas promoções para você</p>
		          </div>
		  		</div>
	      	</div>
		</div>
	</div>
</footer>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript">
  $(function(){
    if ($("#modal-information").length){ 
         $('#modal-information').modal('show');
    }});
</script>
<script src="{% static 'js/scripts.js' %}"></script>

</body>
</html>

apps/product/templates/cadastra.html
{% extends 'base.html' %}

{% block contentPage %}


<div class="container">
  <form method="POST">
    {% csrf_token %}
  <div class="row">
    <div class="col-md-6">
      <label for='form.name.id_tag'>Nome do produto</label>
      {{form.name}}
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for='form.preco.id_tag'>preco</label>
        {{form.preco}}
      </div>
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
      <label for="form.tipyDept.id_for_label">Departamento do produto</label> 
        <div class="form-group">

          {{form.tipyDept}}
        </div>
      
    </div>
    
  </div></div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.description.id_for_label">Descrição do produto</label>
        {{form.description}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.littleDescription.id_for_label">Pequena descrição do produto</label>
        {{form.littleDescription}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="custom-control custom-checkbox mr-sm-2">
        <input class="custom-control-input" type="checkbox" id="{{ form.juros.id_for_label}}" name="{{form.juros.html_name}}" >
        <label class="custom-control-label" for="{{form.juros.id_for_label}}">Juros no produto</label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div>
        <label for="form.maxParc.id_for_label">Máximo de parcelas</label>
        {{form.maxParc}}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6" >
      <div class="custom-file" >

        {{form.image}}
        <label class="custom-file-label" for="customFileLang">Selecionar foto </label>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <input type="submit" name="salvar-produto" value="Salvar">
    </div>


  </div>
</form>
  



</div>
{% endblock %}

apps/product/templates/details.html
{% extends 'base.html' %}
{% load static %}
{%block definitionsMeta%}
  <title>Detalhes do produto</title>
{% endblock%}
{%block contentPage%}



<div class="container">
   <div class="row">
    <div class="col-md-4">
      {% if produto.image%}
      <img src="{{ produto.image.url}}">
      {%else%}
      <img src="{% static 'imagens/produtodefault.png' %}">
      {% endif%}
    </div>
    <div class="col-md-8">
      <div class="detalhes-produto">
        <div class="vendas-produtos">
          <p>
            {{produto.totalVendas}} vendidos
          </p>
        </div>
        <div class="name">
          <h2>{{produto.name}}</h2>
        </div>

        <div class="preco">
          <p>R$</p><h4>{{produto.preco}}</h4>
        </div>

        <div>
          <p>em até {{produto.maxParc}}x de R${{produto.parcelas}}</p>
        </div>


        <div>
          <p>{{produto.description}}</p>
        </div>

        
        <div class="vendedor">
          <p>Vendedor: {{produto.cpfUserPost}}</p>
        </div>
        <div><button class="btn btn-primary">Comprar</button></div>
      </div>
   </div>
 </div>
</div>

{% endblock %}

apps/product/templates/edit-produtt.html
{% extends 'user/profile.html' %}
{% block profileContent %}
  <form method="POST">
    {% csrf_token %}
  <div class="row">
    <div class="col-md-6">
      <label for='form.name.id_tag'>Nome do produto</label>
      {{form.name}}
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for='form.preco.id_tag'>preco</label>
        {{form.preco}}
      </div>
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
      <label for="form.tipyDept.id_for_label">Departamento do produto</label> 
        <div class="form-group">

          {{form.tipyDept}}
        </div>
      
    </div>
    
  </div></div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.description.id_for_label">Descrição do produto</label>
        {{form.description}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.littleDescription.id_for_label">Pequena descrição do produto</label>
        {{form.littleDescription}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="custom-control custom-checkbox mr-sm-2">
        <input class="custom-control-input" type="checkbox" id="{{ form.juros.id_for_label}}" name="{{form.juros.html_name}}" >
        <label class="custom-control-label" for="{{form.juros.id_for_label}}">Juros no produto</label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div>
        <label for="form.maxParc.id_for_label">Máximo de parcelas</label>
        {{form.maxParc}}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6" >
      <div class="custom-file" >

        {{form.image}}
        <label class="custom-file-label" for="customFileLang">Selecionar foto </label>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <input type="submit" name="salvar-produto" value="Salvar">
    </div>


  </div>
</form>
  
{% endblock %}

apps/product/templates/home.html
{%extends 'base.html'%}
{% load static %}
{%block definitionsMeta%}
<title>Easy sale System - Sua venda</title>
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Pacifico" rel="stylesheet">

{% endblock%}
  <
{%block contentPage%}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="carousel-item active home-item-carrousel">
      <img class="d-block w-100" src="{% static 'imagens/carrousel-1.jpg' %}" alt="moda feminina">
      <div class="carousel-caption d-none d-md-block">
        <h5>Tudo para mulheres</h5>
        <p>Encontre os produtos que você deseja</p>
      </div>
    </div>
    <div class="carousel-item home-item-carrousel">
      <img class="d-block w-100" src="{% static 'imagens/carrousel-2.jpg' %}" alt="moda masculina">
      <div class="carousel-caption d-none d-md-block">
        <h5>Produtos para homens</h5>
        <p>Encontre os produtos que você deseja</p>
      </div>
    </div>
    <div class="carousel-item home-item-carrousel">
      <img class="d-block w-100" src="http://fotografia.mayconmatos.com.br/wp-content/uploads/2017/04/Keit-Melo-formosa-Fotografo-Maycon-Matos-01.jpg" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Tudo para mulheres</h5>
        <p>Encontre os produtos que você deseja</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




{%endblock%}

apps/product/templates/listProducts.html
{% extends 'base.html' %}
{% load static %}
{% block definitionsMeta %}
    <title> Produtos - SuaVenda.com</title>
    <link rel="stylesheet" href="{% static 'css/cascade.css' %}">
{% endblock%}


{%block contentPage%}

<div class="container content-pag">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                  </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            <div class="showProdutos " style="display: flex; flex-wrap: wrap">
                {% for produto in produtos %}
                    <div class="flex-item" style="max-width: 18rem;" >
                        <div class="card card text-white bg-primary" style="max-width: 18rem;max-height:403px;height:403px;margin: 10px">
                          {% if produto.image %}
                          <img class="card-img-top" src="{{ produto.image.url }}" alt="{{produto}}">
                          {% else %}
                              <img class="card-img-top" src="{% static 'imagens/produtodefault.png' %}" alt="{{produto}}">
                          {% endif %}
                                      <div class="card-body">
                                        <h5 class="card-title">{{ produto }}</h5>
                                        <p class="card-text">{{ produto.littleDescription   }}</p>
                                        <a href="{{ produto.get_absolute_url }}" class="btn btn-success">Ver mais</a>
                                      </div>
                        </div>
                    </div>
                    {% empty %}
                        <div class="box">
                            <div class="notProduts ">
                                <h1>Não existem produtos cadastrados</h1>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>
    </div>


</div>

{%endblock%}