apps/product/urls.py
from django.urls import path
from apps.product import views

app_name = 'product'

urlpatterns = [
    path('', views.index , name='index'),
    path('produtos/', views.listAllProducts, name='allProducts'),
    path('produtos/<slug:slug>/', views.detail, name='details-product'),
    path('cadastrar',views.cadastrar, name='cadastrar'),
    path('editar/<slug:slug>',views.editProduto, name='editProduct')
]

apps/user/urls.py
from django.urls import path, include
#from django.contrib.auth import authenticate
from apps.user import views
from django.contrib.auth.views import LoginView
app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('registrar-se/', views.register, name='register'),
    path('sair/',views.logoutview,name='logout'),
    path('perfil/',views.dashboard, name='perfil'),
    path('ver-produtos/',views.productOfClient, name='meus-produtos'),
    path('editar-conta/',views.editAccount, name='editar-conta'),
    path('editar-senha/',views.editPassword, name='editar-password')
]

easySale_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('apps.product.urls', namespace='product')),
    path('user/', include('apps.user.urls', namespace='user')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

apps/user/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from datetime import datetime
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,AbstractUser
)
from django.core import validators 
import re
from apps.product.models import Product


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None,is_Admin=False):
        if not email:
            raise TypeError('Informe um email')

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        #password = make_password(password)
        user.set_password(password)
        user.date_joined = datetime.now()
        user.is_active = True
        if(is_Admin):
            return user
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        print(password)
        if password is None:
            raise TypeError('Você precisa de uma senha')
        user = self.create_user(
            email=email,
            password=password,
            username=username,
            is_Admin=True
        )
        user.is_admin = True
        print(user.password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(
        "Nome de usuario",null=False, blank=False, max_length=100, unique=True,default='',
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
         'Nome de usuario só pode conter letras, números ou estes caracteres: @/./+/_'
         , 'invalid')])
    email = models.EmailField("Email", unique=True, null=False, blank=False)
    name = models.CharField('Nome completo' , null=False , blank=False , max_length=100)
    cpf = models.CharField('CPF usuario', primary_key=True, unique=True, max_length=15)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    objects = UserManager()

    def __str__(self):
        return self.name

    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin
    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        ordering = ['username']


class ProdutosComprados(models.Model):
    user = models.ForeignKey(
        User, verbose_name="usuário que comprou",related_name="compras", on_delete=models.CASCADE
        )
    produto = models.ForeignKey(
        Product, verbose_name="usário que comprou",related_name="compras", on_delete=models.CASCADE
        )

apps/user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib import admin
from .models import User
from django.forms import (
    PasswordInput,TextInput, EmailInput)
import re

def validar_cpf(cpf: str) -> bool:

    if not re.match(r'\d{3}\.\d{3}\.\d{3}-\d{2}', cpf):
        return False

    numbers = [int(digit) for digit in cpf if digit.isdigit()]

    if len(numbers) != 11:
        return False

    sum_of_products = sum(a*b for a, b in zip(numbers[0:9], range(10, 1, -1)))
    expected_digit = (sum_of_products * 10 % 11) % 10
    if numbers[9] != expected_digit:
        return False

    sum_of_products = sum(a*b for a, b in zip(numbers[0:10], range(11, 1, -1)))
    expected_digit = (sum_of_products * 10 % 11) % 10
    if numbers[10] != expected_digit:
        return False

    return True


class formCreation(forms.ModelForm):
    password = forms.CharField(label="Senha do lado", widget=forms.PasswordInput(attrs={'placeholder':'Sua senha', 'class':'form-control'}))
    password1 = forms.CharField(label="Confimação de senha", widget=PasswordInput(attrs={'placeholder':'Confime sua senha', 'class':'form-control'}))

    def clean_password1(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password1')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não batem")
        if len(password2)<8:
            raise forms.ValidationError("Sua senha é muito pequena, é indicado uma senha com mais de 8 caracteres")
        return password2

    def clean_cpf(self):

        cpf = str(self.cleaned_data.get('cpf'))

        if(not validar_cpf(cpf)):
            raise forms.ValidationError("CPF invalido")
        return cpf

    def save(self, commit=True):
        user = super(formCreation, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    class Meta:
        model = User
        fields = '__all__'
        exclude = ['is_active', 'is_admin','last_login']
        widgets = {
            'username': TextInput( attrs={'placeholder': 'Username','class':'form-control'}),
            'name':TextInput(attrs={'placeholder':'Seu nome','class':'form-control'}),
            'email':EmailInput(attrs={'class':'form-control','placeholder':'seunome@dominio.com'}),
            'cpf':TextInput(attrs={'class':'form-control'})
        }

class editAccount(forms.Form):
    email = forms.EmailField(label='Email ', required=False)
    username = forms.CharField(label='username',required=False)
    cpf = forms.DecimalField(label='CPF')
    

apps/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from easySale_System import settings
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from .forms import (formCreation, editAccount)
from django.shortcuts import get_object_or_404
# Views da app User.
root ='user/'
from apps.product.models import (Product, CustomManager)
from .models import User
@login_required
def logoutview(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


def register(request):
    if request.method == "POST":
        form = formCreation(request.POST)
        if form.is_valid():
            form.save()

            messages.add_message(request, messages.SUCCESS, 'Cadastro feito com sucesso, faça login',extra_tags="alert alert-success")
            return redirect(settings.LOGIN_URL)
    else:
        form = formCreation()

    context = {
        'form': form
    }
    return render(request, root+'register.html', context)


@login_required
def dashboard(request):
    return render(request , root+'profile.html')


@login_required
def productOfClient(request):
    print('oi')
    produtos = Product.objects.getProductsForUser(request.user)
    print("dois")
    context =  {
        'produtos' : produtos
    }
    return render(request, root+'meus-produtos.html', context)

@login_required
def editAccount(request):
    context = {}

    if request.method == 'POST':
        print(form.cleaned_data['username'])
        print(form.cleaned_data['cpf'])
        print(form.cleaned_data['name'])

        if form.is_valid():
            #form.save()
            context['success'] = True
    else:
        form = editAccount()
    context['form'] = form
    return render(request, root+'editinformation.html', context)

@login_required
def editPassword(request):
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST , user = request.user)
        if form.is_valid():
            form.save()
            context['success'] = True

    else:
        form = PasswordChangeForm(user = request.user)
    context['form'] = form
    return render(request , root+'edit_password.html',context)

apps/user/templates/user/cadastraprodutos.html
{% extends 'user/profile.html' %}

{% block profileContent %}


<div class="container">
  <form method="POST">
    {% csrf_token %}
  <div class="row">
    <div class="col-md-6">
      <label for='form.name.id_tag'>Nome do produto</label>
      {{form.name}}
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for='form.preco.id_tag'>preco</label>
        {{form.preco}}
      </div>
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
      <label for="form.tipyDept.id_for_label">Departamento do produto</label> 
        <div class="form-group">

          {{form.tipyDept}}
        </div>
      
    </div>
    
  </div></div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.description.id_for_label">Descrição do produto</label>
        {{form.description}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div>
        <label for="form.littleDescription.id_for_label">Pequena descrição do produto</label>
        {{form.littleDescription}}
      </div>
      
    </div>
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="custom-control custom-checkbox mr-sm-2">
        <input class="custom-control-input" type="checkbox" id="{{ form.juros.id_for_label}}" name="{{form.juros.html_name}}" >
        <label class="custom-control-label" for="{{form.juros.id_for_label}}">Juros no produto</label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div>
        <label for="form.maxParc.id_for_label">Máximo de parcelas</label>
        {{form.maxParc}}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6" >
      <div class="custom-file" >

        {{form.image}}
        <label class="custom-file-label" for="customFileLang">Selecionar foto </label>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <input type="submit" name="salvar-produto" value="Salvar">
    </div>


  </div>
</form>
  



</div>
{% endblock %}

apps/user/templates/user/editinformation.html
{% extends 'user/profile.html' %}
{% load staticfiles %}
{% block definitionsMeta %}
  <title>Cadastre-se</title>
  <script type="text/javascript" href='https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.min.js'></script>
  
{% endblock %}

{% block profileContent %}

<div class="contentPage"> 
  <div class="container">
    <div class="title-cadastro">
      <h2>Edição de dados</h2>
    </div>
    <form method="POST" class='d-flex flex-column '>
      {% csrf_token %} 
      <div class="row">
          <div class="erros-list">
            {% for erro in form.non_field_errors  %}
              <p class="alert alert-danger erro-alert">{{erro}}</p>
            {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-4 mb-3">
          <label for="form.name.id_tag"> Digite seu nome</label>
          {{form.name}}
        </div>
        <div class="erros-list">
            {% for erro in form.name.errors  %}
              <p class="alert alert-danger erro-alert">{{erro}}</p>
            {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.username.id_tag}}">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
            </div>
            {{form.username}}
          </div>
          <div class="erros-list">
              {% for erro in form.username.errors  %}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.email.id_tag}}">Endereço de e-mail</label>
          {{form.email}}
          <small id="emailHelp" class="form-text text-muted">Nós não compartilharemos seu endereço, fique tranquilo.</small>
          <div class="erros-list">
            {% for erro in form.email.errors%}
              <p class="alert alert-danger">{{erro}}</p>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.cpf.id_tag}}">Seu cpf</label>
          {{form.cpf}}
          <small id="emailHelp" class="form-text text-muted">Verifque nossas politicas, por segurança..</small>
          <div class="erros-list">
              {% for erro in form.cpf.errors%}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.password.id_tag}}">Sua senha</label>
          {{form.password}}
          <small id="emailHelp" class="form-text text-muted">As senhas diferem de maiusculas e minusculas.</small>
            <div class="erros-list">
                {% for erro in form.password.errors%}
                  <p class="alert alert-danger">{{erro}}</p>
                {% endfor %}
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.password1.id_tag}}">Confimação de senha</label>
          {{form.password1}}
          <div class="erros-list">
              {% for erro in form.password1.errors%}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <button type="submit" class="btn btn-success"value="Submit">Salvar modificações </button>

      </div>
    </form>
  </div>





<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-trigger").dropdown();
    $('#id_cpf').mask('000.000.000-00', {reverse: true});


});
</script>
{% endblock %}

apps/user/templates/user/index.html
{% extends 'base.html' %}

apps/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block definitionsMeta %}
  <title>Faça login</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


{% endblock %}

{% block contentPage %}



<section class="">
    <div class="container">
        <div class="row">
          
          <div class="col-md-4 login-sec">
              <h2 class="text-center">Faça login</h2>
              <form class="login-form" method="POST">
                 {% csrf_token %}
                {% for erro in form.non_field_errors  %}
                  <p class="alert alert-danger erro-alert">{{erro}}</p>
                {% endfor %}
              <div class="form-group">
                <label for="exampleInputEmail1" class="text-uppercase">Username</label>
                <input class="form-control" type="text" id="{{ form.username.id_for_label}}" name="{{form.username.html_name}}" maxlength="30" >
                
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1" class="text-uppercase">Password</label>
                <input class="form-control" type="password" id="{{ form.password.id_for_label}}" name="{{form.password.html_name}}" maxlength="30" >
              </div>
              
              
                <div class="form-check">
                <label class="form-check-label">
                  <input type="checkbox" class="form-check-input">
                  <small>Lembrar</small>

                </label>
                <button type="submit" class="btn btn-login float-right">Submit</button>
                <a href="{% url 'user:register' %}" class="btn btn-primary"> Clique aqui para registrar-se</a>
              </div>
  
          </form>

    </div>
    <div class="col-md-8 banner-sec">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                 <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
            <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="https://static.pexels.com/photos/33972/pexels-photo.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>Coloque seus produtos a venda</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>  
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="https://images.pexels.com/photos/7097/people-coffee-tea-meeting.jpg" alt="Secound slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>Alcançe milhares de usuários</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>  
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="https://images.pexels.com/photos/872957/pexels-photo-872957.jpeg" alt="Three slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>Alavance seu orçamento</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>  
    </div>
  </div>
  </div>     
        
    </div>
  </div>
</div>
</section>

{% endblock %}

apps/user/templates/user/meus-produtos.html
{% extends 'user/profile.html'%}
{% load static %}
{% block profileContent %}
	
		{% for produto in produtos%}
		<div class="row ">
			<div class="col-md-4">
				{% if produto.image%}
					<img src="{{ produto.image.url }}" style="max-width: 200px">
				{% else %}
					<img src="{% static 'imagens/produtodefault.png' %}" style="max-width: 200px">
				{% endif %}
			</div>
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-6"><h1>{{ produto.name }}</h1></div>
					<div class="col-md-6"><h3>R${{ produto.preco}}</h3></div>
				</div>
				<div class="row">
					<div class="col-md-12">
						{{produto.littleDescription|linebreaks}}
					</div>
					<div class="col-md-12">
						<h5>Descrição do produto:</h5> {{produto.description|linebreaks}}
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div><p>Máximo parcelamento {{produto.maxParc}}</p></div>
					</div>
					<div class="col-md-4">
						<div><p>Departamento: {{produto.tipyDept}}</p></div>
					</div>
					<div class="col-md-4">
						<div><a class="btn btn-success" href="{% url 'product:editProduct' slug=produto.get_absolute_url %}" >Editar produto </a></div>
					</div>

				</div>
			</div>
		</div>
		
		{% endfor %}

	
{% endblock %}

apps/user/templates/user/profile.html
{% extends 'base.html' %}

{% block contentPage %}
<div class="container">
	<div class="row">
		<div class='col-md-3'>
			<nav class="nav flex-column accounts-menu">
			  <a class="nav-link active btn btn-primary" href="{% url 'user:meus-produtos' %}">Ver meus produtos</a>
			  <a class="nav-link btn btn-primary" href="{% url 'product:cadastrar' %}">Adcionar produto</a>
			  <a class="nav-link btn btn-primary" href="{% url 'user:editar-conta' %}">Editar conta</a>
			  <a class="nav-link btn btn-primary" href="{% url 'user:editar-password' %}">Editar senha</a>
			  <a class="nav-link disabled btn btn-danger" href="#">Disabled</a>
			</nav>
		</div>
		<div class="col-md-8">
			{% block profileContent %}
			{% endblock%}
		</div>
	</div>
</div>
{% endblock%}

apps/user/templates/user/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block definitionsMeta %}
  <title>Cadastre-se</title>
  <script type="text/javascript" href='https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.min.js'></script>
  
{% endblock %}

{% block contentPage%}

<div class="contentPage"> 
  <div class="container">
    <div class="title-cadastro">
      <h2>Cadastro de usuários</h2>
    </div>
    <form method="POST" class='d-flex flex-column '>
      {% csrf_token %} 
      <div class="row">
          <div class="erros-list">
            {% for erro in form.non_field_errors  %}
              <p class="alert alert-danger erro-alert">{{erro}}</p>
            {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-4 mb-3">
          <label for="form.name.id_tag"> Digite seu nome</label>
          {{form.name}}
        </div>
        <div class="erros-list">
            {% for erro in form.name.errors  %}
              <p class="alert alert-danger erro-alert">{{erro}}</p>
            {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.username.id_tag}}">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
            </div>
            {{form.username}}
          </div>
          <div class="erros-list">
              {% for erro in form.username.errors  %}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.email.id_tag}}">Endereço de e-mail</label>
          {{form.email}}
          <small id="emailHelp" class="form-text text-muted">Nós não compartilharemos seu endereço, fique tranquilo.</small>
          <div class="erros-list">
            {% for erro in form.email.errors%}
              <p class="alert alert-danger">{{erro}}</p>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.cpf.id_tag}}">Seu cpf</label>
          {{form.cpf}}
          <small id="emailHelp" class="form-text text-muted">Verifque nossas politicas, por segurança..</small>
          <div class="erros-list">
              {% for erro in form.cpf.errors%}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.password.id_tag}}">Sua senha</label>
          {{form.password}}
          <small id="emailHelp" class="form-text text-muted">As senhas diferem de maiusculas e minusculas.</small>
            <div class="erros-list">
                {% for erro in form.password.errors%}
                  <p class="alert alert-danger">{{erro}}</p>
                {% endfor %}
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="{{form.password1.id_tag}}">Confimação de senha</label>
          {{form.password1}}
          <div class="erros-list">
              {% for erro in form.password1.errors%}
                <p class="alert alert-danger">{{erro}}</p>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <button type="submit" class="btn btn-success"value="Submit">Cadastrar-se</button>
        <button type="reset" class="btn btn-danger" value="Reset">Excluir dados</button>
      </div>
    </form>
  </div>





<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".dropdown-trigger").dropdown();
    $('#id_cpf').mask('000.000.000-00', {reverse: true});


});
</script>
{% endblock %}

apps/user/templates/user/teste.html
{% extends "base.html" %}

{% block contentPage %}


{% endblock %}
<section class="container">
  <div class="container-login">
    <div class="row">
      <div class="col-md-4">
        <h2 class="text-center">Faça login</h2>
              <form class="login-form" method="POST">
                {% csrf_token %}
                {{ form.non_field_erros }}
              <div class="form-group">
                <label for="exampleInputEmail1" class="text-uppercase">Username</label>
                <input class="form-control" type="text" id="{{ form.username.id_for_label}}" name="{{form.username.html_name}}" maxlength="30" >
                
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1" class="text-uppercase">Password</label>
                <input class="form-control" type="password" id="{{ form.password.id_for_label}}" name="{{form.password.html_name}}" maxlength="30" >
              </div>
              
              
                <div class="form-check">
                <label class="form-check-label">
                  <input type="checkbox" class="form-check-input">
                  <small>Lembrar</small>

                </label>
                <button type="submit" class="btn btn-login float-right">Submit</button>
                <a href="{% url 'user:register' %}" class="btn btn-primary"> Clique aqui para registrar-se</a>
              </div>
  
          </form>
      </div>
      <div class="col-md-8">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
  <img src="{% static 'imagens/photos.jpg' %}" alt="">
  <div class="carousel-caption d-none d-md-block">
    <h5>Segurança sempre</h5>
    <p>Nós contamos com uma série de módulos de segurança</p>
  </div>
</div>
    <div class="carousel-item">
  <img src="{% static 'imagens/ecomerce.jpg' %}" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>Tenha alto lucro</h5>
    <p>Nós cobramos uma pequena taxa sobre nossos serviços</p>
  </div>
</div>
    <div class="carousel-item">
  <img src="{% static 'imagens/ecomerce2.jpg' %}" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>Compre sem sair de casa</h5>
    <p>Sua comodidade é nossa obrigação, compre e deixe tudo com a gente</p>
  </div>
</div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
      </div>

</section>